---
version: '3'
services:
  django:
    build:
      context: .
    command: python manage.py runserver
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
