---
version: '3'
services:
  django:
    build:
      context: .
    command: gunicorn -b 0.0.0.0:8000 --access-logfile - tamedrift.wsgi
    environment:
      - DEBUG=True
      - SECRET_KEY=mysecretkey
      - DATABASE_URL=postgres://admin:XcPOzIwK6XXKL63r6C2ch4RsCaoVGIiR@dpg-cjd8p02nip6c73efmftg-a.oregon-postgres.render.com/tamedrift
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: "redis:latest"
