---
version: '3'
services:
  django:
    build:
      context: .
    command: gunicorn tamedrift.wsgi
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
