# Use the official Python image as the base image
FROM python:3.11

# Set environment variables for Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV POETRY_VIRTUALENVS_CREATE 0

# Install Poetry
RUN pip install poetry==1.2.2

# Set the working directory in the container
WORKDIR /app

# Copy your Django project files into the container
COPY . /app/

# Install Python dependencies with Poetry
RUN poetry install --without dev
