---
version: '3'
services:
  django:
    build:
      context: .
    command: gunicorn -b 0.0.0.0:8000 --access-logfile - tamedrift.wsgi
    environment:
      - DEBUG=True
      - SECRET_KEY=mysecretkey
      - DATABASE_URL=postgres://admin:TSKitdWtyPUEYT5y2iJhVqE9KU8KUSgV@dpg-cjiasg337aks73d1kbsg-a.oregon-postgres.render.com/tamedrift_dtcg
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: "redis:latest"
