---
databases:
  - name: tamedrift-dev-db
    databaseName: tamedrift
    user: admin

services:
  - type: redis
    name: redis-dev
    ipAllowList: # required
    - source: 0.0.0.0/0
      description: everywhere
    plan: free # optional (defaults to starter instance type)
  - type: web
    name: tamedrift-dev-backend
    runtime: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tamedrift-dev-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-dev
          property: connectionString
