---
databases:
  - name: tamedrift-db
    databaseName: tamedrift
    user: admin
services:
  - type: web
    name: tamedrift-backend
    runtime: docker
    dockerCommand: gunicorn tamedrift.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tamedrift-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
  - type: redis
    name: redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
  - type: cron
    name: tier-list
    runtime: docker
    dockerfilePath: ./Dockerfile.scripts
    dockerCommand: python manage.py runscript tier_list
    schedule: 0 */8 * * *
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tamedrift-db
          property: connectionString
      - key: API_URL
        value: https://tamedrift-backend.onrender.com
