---
databases:
  - name: tamedrift-dev-db
    databaseName: tamedrift
    user: admin
services:
  - type: redis
    name: redis-dev
    region: frankfurt
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free
  - type: web
    name: tamedrift-dev-backend
    region: frankfurt
    runtime: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tamedrift-dev-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-dev
          property: connectionString
  - type: cron
    name: tier-list
    runtime: docker
    dockerfilePath: ./Dockerfile.scripts
    dockerCommand: python manage.py runscript tier_list
    schedule: 0 0 * * 1,5
