# Generated by Django 4.2.2 on 2023-06-28 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildrift_cn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='id',
        ),
        migrations.AlterField(
            model_name='hero',
            name='heroId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='herostatistic',
            name='hero_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wildrift_cn.hero'),
        ),
    ]
