# Generated by Django 4.2.3 on 2023-07-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wildrift_cn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="championstatistic",
            name="appear_pct",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="championstatistic",
            name="forbid_pct",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="championstatistic",
            name="win_pct",
            field=models.IntegerField(),
        ),
    ]
