# Generated by Django 4.2.3 on 2023-07-29 18:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wildrift_cn", "0002_alter_championstatistic_appear_pct_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChampionStatistic",
            new_name="TierList",
        ),
    ]
