# Generated by Django 4.2.3 on 2023-08-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wildrift_cn", "0004_alter_champion_heroid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="champion",
            name="heroId",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="tierlist",
            name="id",
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
