class Catalog:
    roles = {
        "法师": "Mage",
        "刺客": "Assassin",
        "战士": "Bruiser",
        "辅助": "Support",
        "坦克": "Tank",
        "射手": "ADC",
    }

    names = {
        "亚托克斯": "Aatrox",
        "亚索": "Yasuo",
        "伊泽瑞尔": "Ezreal",
        "伊芙琳": "Evelynn",
        "佐伊": "Zoe",
        "内瑟斯": "Nasus",
        "凯南": "Kennen",
        "凯尔": "Kayle",
        "凯特琳": "Caitlyn",
        "凯隐": "Kayn",
        "加里奥": "Galio",
        "努努和威朗普": "Nunu",
        "劫": "Zed",
        "卡兹克": "Khazix",
        "卡尔玛": "Karma",
        "卡特琳娜": "Katarina",
        "卡莎": "Kaisa",
        "卡萨丁": "Kassadin",
        "卡蜜尔": "Camille",
        "卢锡安": "Lucian",
        "厄加特": "Urgot",
        "厄运小姐": "MissFortune",
        "古拉加斯": "Gragas",
        "吉格斯": "Ziggs",
        "嘉文四世": "Jarvan IV",
        "图奇": "Twitch",
        "墨菲特": "Malphite",
        "奥恩": "Orianna",
        "奥拉夫": "Olaf",
        "奥瑞利安·索尔": "Aurelion Sol",
        "奥莉安娜": "Orianna",
        "娑娜": "Sona",
        "娜美": "Nami",
        "孙悟空": "Wukong",
        "安妮": "Annie",
        "崔丝塔娜": "Tristana",
        "崔斯特": "Twisted Fate",
        "布兰德": "Brand",
        "布里茨": "Blitzcrank",
        "布隆": "Braum",
        "希瓦娜": "Shyvana",
        "库奇": "Corki",
        "德莱厄斯": "Darius",
        "德莱文": "Draven",
        "悠米": "Yuumi",
        "慎": "Shen",
        "拉克丝": "Lux",
        "拉莫斯": "Rammus",
        "提莫": "Teemo",
        "斯维因": "Swain",
        "易": "Master Yi",
        "李青": "Lee Sin",
        "杰斯": "Jayce",
        "格温": "Gwen",
        "格雷福斯": "Graves",
        "永恩": "Yone",
        "沃利贝尔": "Volibear",
        "沃里克": "Warwick",
        "泰达米尔": "Tryndamere",
        "泽丽": "Zeri",
        "洛": "Rakan",
        "派克": "Pyke",
        "潘森": "Pantheon",
        "烬": "Jhin",
        "瑟提": "Sett",
        "璐璐": "Lulu",
        "盖伦": "Garen",
        "索拉卡": "Soraka",
        "维迦": "Veigar",
        "艾克": "Ekko",
        "艾希": "Ashe",
        "艾瑞莉娅": "Irelia",
        "莉莉娅": "Lillia",
        "莎弥拉": "Samira",
        "莫甘娜": "Morgana",
        "菲兹": "Fizz",
        "菲奥娜": "Fiora",
        "萨勒芬妮": "Seraphine",
        "蒙多医生": "Dr. Mundo",
        "蔚": "Vi",
        "蕾欧娜": "Leona",
        "薇古丝": "Vex",
        "薇恩": "Vayne",
        "诺提勒斯": "Nautilus",
        "贾克斯": "Jax",
        "赛娜": "Senna",
        "赛恩": "Sion",
        "赵信": "Xin Zhao",
        "辛吉德": "Singed",
        "迦娜": "Janna",
        "金克丝": "Jinx",
        "锐雯": "Riven",
        "锤石": "Thresh",
        "阿克尚": "Akshan",
        "阿利斯塔": "Alistar",
        "阿卡丽": "Akali",
        "阿木木": "Amumu",
        "阿狸": "Ahri",
        "雷克顿": "Renekton",
        "雷恩加尔": "Rengar",
        "霞": "Xayah",
        "韦鲁斯": "Varus",
        "黛安娜": "Diana",
    }


catalog = Catalog()
